### ISSUE TITLE
Loading checkpoint weights

### ISSUE THREAD

**Issue by JoseLuisNeves** [xiongyiheng/Prior-RadGraphFormer#4]
Hello, 
I am trying to perform inference for an image tensor using the checkpoint weights you provided. My code can be reduced to this

from models.relationformer_2D import build_relationformer as build_model

with open(config_file) as f:
      config = yaml.load(f, Loader=yaml.FullLoader)
config = dict2obj(config)

model = build_model(config)

checkpoint = torch.load(checkpoint_path,  map_location='cpu')
model.load_state_dict(checkpoint)

img_tensor = torch.load(img_tensor_path) 
 with torch.no_grad():
       output = model(img_tensor)

However, I am getting this error:

Traceback (most recent call last):
  File "my_inference.py", line 65, in <module>
    main()
  File "my_inference.py", line 56, in main
    model = load_checkpoint(model, args.checkpoint)
  File "my_inference.py", line 41, in load_checkpoint
    model.load_state_dict(checkpoint)
  File "C:\Users\josen\anaconda3\envs\pradgraph\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RelationFormer:
        Missing key(s) in state_dict: "backbone.0.body.conv0.weight"(...) "input_proj.3.1.bias".
        Unexpected key(s) in state_dict: "net", "optimizer", "scheduler".

How do you recommend loading the weights and performing inference (if I understood the code correctly, inference.py already takes the model outputs(embeddings) as inputs)?

**Comment by TumVink** [comment]
@xiongyiheng could you assist here?

**Comment by JoseLuisNeves** [comment]
In the meantime, I forked your repository and created a code called my_inference.py that receives an image and uses the model still without assimilation to extract the knowledge graph. 

In the main function of this code I do this:

def main():
    model = load_model(config)

    model = load_checkpoint(model, args.checkpoint)
    
    # Load image
    img_path = args.img_path
    img_tensor = load_img(img_path)

    # Perform inference
    h, out = perform_inference(model, img_tensor)
    
    # Process model outputs
    #asm = model.asm
    #project = model.project
    relation_embed = model.relation_embed
    out = graph_infer(h, out, relation_embed=relation_embed) #asm=asm, project=project)

    pred_edges = [{'pred_rels': pred_rels, 'pred_edge': pred_edge, 'pred_rel_score': pred_rel_score} for
                      pred_rels, pred_edge, pred_rel_score in
                      zip(out['pred_rels'], out['pred_rels_class'], out['pred_rels_score'])]
    pred_nodes = [{'tokens': pred_token, 'labels': pred_label} for pred_token, pred_label in
                      zip(out['pred_tokens'], out['pred_labels'])]
    
    gt_tokens = map_cls_name(pred_nodes[0]['tokens'],"tokens",None)

    #print('pred edges ', pred_edges)

    kg = map_cls_name(pred_edges[0], "edges", gt_tokens)

Where:

def load_checkpoint(model, checkpoint_path):
    checkpoint = torch.load(checkpoint_path, map_location='cpu')
    _,_= model.load_state_dict(checkpoint['net'], strict=False)
    model.eval()
    return model

def perform_inference(model, img_tensor):
    with torch.no_grad():
        h, out = model([img_tensor])
    return h, out 

and graph_infer() is your function from inference.py.

If you could just take a look and see if it makes sense, I would much appreciate it.

**Comment by xiongyiheng** [comment]
For inference, you can refer to evaluator.py from line 132 (how to use functions in inference.py). And for loading weights, you can refer to train.py from line 151. Hope this can solve you problem. Feel free to ask here if you have any additional questions :)

**Comment by JoseLuisNeves** [comment]
Thank you! I think I am doing as you suggested, I just have to include the assimilation part now (right now I am obtaining almost the same knowledge graph for every image, I thought the problem could be for not loading the weights correctly, but it must be because of something else). I have actually loved your work and will continue to work on it, so I will be having more questions for sure!
